apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  # Important: Name must be the same as the Resource Name!
  name: cc-aks-tf-ui
spec:
  type: 0
  ResourceID: /subscriptions/%SUBSCRIPTION_ID%/resourcegroups/cc-aks-tf-nodes-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cc-aks-tf-ui
  ClientID: %CLIENT_ID%
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: cc-aks-tf-ui-identity-binding
spec:
  AzureIdentity: cc-aks-tf-ui
  Selector: cc-aks-tf-ui-selector
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-retain
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cyclecloud-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 128Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: cycle
    aadpodidbinding: cc-aks-tf-ui-selector
  name: cycle
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cycle
  strategy: {}
  template:
    metadata:
      labels:
        run: cycle
        aadpodidbinding: cc-aks-tf-ui-selector
    spec:
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      containers:
      - env:
        - name: JAVA_HEAP_SIZE
          value: "4096"
        - name: CYCLECLOUD_USERNAME
          value: "%CYCLECLOUD_USERNAME%"
        - name: CYCLECLOUD_PASSWORD
          value: "%CYCLECLOUD_PASSWORD%"
        - name: CYCLECLOUD_STORAGE
          value: "%CYCLECLOUD_STORAGE%"
        - name: CYCLECLOUD_USER_PUBKEY
          value: "%CYCLECLOUD_USER_PUBKEY%"
        - name: CYCLECLOUD_RESOURCE_GROUP
          value: "%CYCLECLOUD_RESOURCE_GROUP%"
        image: %CYCLECLOUD_CONTAINER_IMAGE%
        resources:
          requests:
            memory: "10Gi"
          limits:
            memory: "10Gi"
        command: ["/bin/bash"]
        args: ["-c", "chmod +x scripts/run_cyclecloud.sh && ./scripts/run_cyclecloud.sh"]
        name: cycle
        ports:
        - containerPort: 443

        livenessProbe:
          httpGet:
            path: /health_monitor
            port: 443
            scheme: HTTPS
          failureThreshold: 15
          timeoutSeconds: 60
          periodSeconds: 60
          initialDelaySeconds: 400

        readinessProbe:
          httpGet:
            path: /health_monitor
            port: 443
            scheme: HTTPS
          failureThreshold: 30
          initialDelaySeconds: 600
          periodSeconds: 10

        volumeMounts:
        - mountPath: "/opt"
          name: cyclecloud-data-volume
      volumes:
      - name: cyclecloud-data-volume
        persistentVolumeClaim:
          claimName: cyclecloud-data

---
apiVersion: v1
kind: Service
metadata:
  name: cycle
  #  Uncomment to disable Public IP
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  selector:
    run: cycle

