apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ include "cyclecloud.fullname" . }}
  labels:
    {{- include "cyclecloud.labels" . | nindent 4 }}
spec:
  type: 0
  resourceID: {{ .Values.azureIdentity.resourceID }}
  clientID: {{ .Values.azureIdentity.clientID }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ include "cyclecloud.fullname" . }}
  labels:
    {{- include "cyclecloud.labels" . | nindent 4 }}
spec:
  azureIdentity: {{ include "cyclecloud.fullname" . }}
  selector: cc-aks-tf-ui-selector