apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cyclecloud-data
  labels:
    {{- include "testing.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 128Gi