apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cyclecloud.fullname" . }}
  labels:
    {{- include "cyclecloud.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 128Gi