apiVersion: v1
kind: Service
metadata:
  name: cycle
  labels:
    {{- include "testing.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  selector:
    run: cycle